import type { Product, Settings } from "@pitch/contracts";
export const defaults: Settings = {
  business_name: "Pitch Lab Athletics",
  business_email: "",
  business_phone: "",
  business_timezone: "America/Chicago",
  booking_window_days: 45,
  minimum_booking_notice_hours: 12,
  free_reschedule_notice_hours: 48,
  late_reschedule_fee_cents: 1000,
  cancellation_fee_cents: 1000,
  premium_capacity: 12,
  credit_rollover_months: 1,
  video_response_target_hours: 24,
  payment_grace_days: 3,
  retention_discount_enabled: false,
};
// Development catalog only; checkout always resolves live database products and Stripe prices.
export const catalog: Product[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    slug: "private-session",
    name: "1-Hour Session",
    description: "A focused session. A clear next step.",
    product_type: "lesson",
    price_cents: 4000,
    billing_interval: null,
    benefits: [
      "60-minute private lesson",
      "Mechanical assessment",
      "Individualized coaching",
      "Personalized drill recommendations",
    ],
    active: true,
    display_order: 1,
    capacity: null,
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    slug: "recorded-session",
    name: "Recorded 1-Hour Session",
    description: "See your mechanics. Understand your adjustments.",
    product_type: "recorded_lesson",
    price_cents: 6000,
    billing_interval: null,
    benefits: [
      "60-minute private lesson",
      "Recorded mechanics review",
      "Coach-led breakdown",
      "Personalized drill recommendations",
    ],
    active: true,
    display_order: 2,
    capacity: null,
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    slug: "premium",
    name: "Premium Coaching",
    description: "A coach in your corner. A plan for your development.",
    product_type: "premium",
    price_cents: 15000,
    billing_interval: "month",
    benefits: [
      "4 private-training credits monthly",
      "Weekly throwing programming",
      "Video feedback · approximately 24 hours",
      "Monthly progress report",
      "Game-Day Coaching Support, by arrangement",
    ],
    active: true,
    display_order: 3,
    capacity: null,
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    slug: "video-analysis",
    name: "Video Data Analysis",
    description: "Your mechanics, with a fresh perspective.",
    product_type: "video",
    price_cents: 3000,
    billing_interval: null,
    benefits: [
      "Send video directly to Coach Jacob",
      "Individualized mechanics analysis",
      "Corrective recommendations",
      "Relevant drills",
    ],
    active: true,
    display_order: 4,
    capacity: null,
  },
];
